// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZsLIIT_zkTO6-zcl-X8FGidgJRs4mbo',
    appId: '1:929526377021:web:8a230de43d2bf1e7c7d854',
    messagingSenderId: '929526377021',
    projectId: 'ocebot2-6f7b6',
    authDomain: 'ocebot2-6f7b6.firebaseapp.com',
    storageBucket: 'ocebot2-6f7b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrMxKAm1OoBYNFCowkxVwZb_Lmo0G_G6U',
    appId: '1:929526377021:android:77f8b1ddb321a609c7d854',
    messagingSenderId: '929526377021',
    projectId: 'ocebot2-6f7b6',
    storageBucket: 'ocebot2-6f7b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAixNVQ1odegP_HvRJ7g87kgIzVo2yoKcA',
    appId: '1:929526377021:ios:de0cc5e876edc3bac7d854',
    messagingSenderId: '929526377021',
    projectId: 'ocebot2-6f7b6',
    storageBucket: 'ocebot2-6f7b6.appspot.com',
    iosClientId: '929526377021-hcghea5s3dq1e71uhf4kau4dv9okm14a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocebot20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAixNVQ1odegP_HvRJ7g87kgIzVo2yoKcA',
    appId: '1:929526377021:ios:de0cc5e876edc3bac7d854',
    messagingSenderId: '929526377021',
    projectId: 'ocebot2-6f7b6',
    storageBucket: 'ocebot2-6f7b6.appspot.com',
    iosClientId: '929526377021-hcghea5s3dq1e71uhf4kau4dv9okm14a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ocebot20',
  );
}
